bind y new-session -c '#{pane_current_path}'
bind r source-file ~/.tmux.conf \; display ".tmux.conf reloaded!"
set -g status-left-length 35
set -g mouse on
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "xclip -in -selection clipboard"
